### ISSUE TITLE
KeyError in Rpi Microagent

### ISSUE THREAD

**Issue by eva6370** [mF2C/ResourceManagement#73]
https://github.com/mF2C/ResourceManagement/blob/af10fa4404cf8bbb4b034119630841649a9966cc/Resource-Categorization/ARM-based/device_static.py#L26

```python
The Resource-Categorization module is about to be start.....
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:46070/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Oct/2019 11:39:36] "POST /api/v1/resource-management/categorization/start/ HTTP/1.1" 200 -
Exception in thread sta:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 104, in static
    stat = static_info()
  File "/var/app/device_static.py", line 180, in static_info
    a=hwsw_info()
  File "/var/app/device_static.py", line 27, in hwsw_info
    cpu_clock_speed = a['hz_advertised']
KeyError: 'hz_advertised'
```

**Comment by ssgUPC** [comment]
That's my fault!!! forget to add try-catch

**Comment by ALEJANDROJ19** [comment]
Solved.
